### ISSUE TITLE
Seeking causing reload

### ISSUE THREAD

**Issue by fieldofsheep** [bbc/html5-video-compositor#10]
When I seek a video it continues to call the 'this.element.load' method which if we are in the case of using webservice to render the video a response causes the web service to be hit many many times.

The system should have a way in which unless the track changes AND unless the video has not already been loaded that it should stay 'As Is' on seeking.

**Comment by MatthewShotton** [comment]
Commit c2463bf1bfe7cdd392c7fdf83a996af21d0a1dc5 goes some way to fixing this. If you're within a video source that's currently playing, or if there's videos being buffered for future play  it won't force a reload if you seek within the bounds of the pre-loaded media. 

There's still an open question about how to handle mediasources that have finished playing. Currently the behaviour is they are disposed of as soon as they've finished. This is to help try and keep the browser responsive by not having a whole load of videos elements sitting around behind the scenes. This will probably not be the desired behaviour in all use-cases.

One potential solution is to add a property to the video compositor which lets you set how many already played mediasources to keep alive.

I'll leave this issue open until a sensible solution is implemented.

**Comment by MatthewShotton** [comment]
VideoCompositor now has preloadTime and postPlayTime properties which allow you to set how far in the future to look for mediasources to preload and how far back in time to keep mediasources before destroying them.
