### ISSUE TITLE
'demo' assets missing

### ISSUE THREAD

**Issue by mcorb** [bbc/html5-video-compositor#12]
The first port of call, 'demo' doesn't work out of the box. It contains references to asset files:

assets/wtf_greenscreen_fast.mp4
assets/weather-plate.png
["/assets/lut.png", "/assets/bronze.png", "/assets/dark.png", "/assets/scifi.png", "/assets/vivid.png"]
...

These files don't exist in-tree, nor could I find any reference on where to download them from.

It'd be great to have a quick demo that works so newcomers can get a feel for what this library does before getting involved with the tutorial.

(If the assets aren't redistributable, it might be better to delete the demo and include a simple working example instead so as not to send users on an asset hunt)

**Comment by MatthewShotton** [comment]
Hi mcorb, Thanks for spotting this. I've removed the demo directory for now. I'll investigate a more suitable/functional solution for quickly demonstrating what the library can do for new users.
