### ISSUE TITLE
Subdivide

### ISSUE THREAD

**Issue by philholden** [bbc/html5-video-compositor#7]
Not really an issue

Just incase you find it helpful. I created a UI component called Subdivide very much with live video editing in mind you may find it helpful for building editors.

https://www.youtube.com/watch?v=3ePrvrx9otk
https://github.com/philholden/subdivide

**Comment by MatthewShotton** [comment]
Hi Phil,
Thanks for passing that on. Looks very interesting. I'll pass it onto some colleagues who may find it useful.
Marking this as closed now.
