### ISSUE TITLE
OS platform compatibility?

### ISSUE THREAD

**Issue by sp00x** [bbc/html5-video-compositor#8]
There are no indicators of OS platform compatibility listed, but I didn't have any luck with the build script on Windows, so I am guessing *nix only? 

"npm run build" fails at 

```
> html5-video-compositor@0.0.1 build D:\test\html5-video-compositor
> ./node_modules/webpack/bin/webpack.js --optimize-minimize --config webpack.config.js && ./node_modules/webpack/bin/webpack.js --config webpack.commonjs2.config.js

'.' is not recognized as an internal or external command,
operable program or batch file.
```

Adding "node " in front of the .js references in the scripts-section of the package.json file fixes it of course.

Maybe just clarify if this is supposed to work on Windows or not, and fix the package.json script commands?

**Comment by sp00x** [comment]
Well it does appear to build and work once the package.json file is fixed with adding the missing "node " bits!

**Comment by MatthewShotton** [comment]
Hi sp00x, thanks for spotting that! We typically build on *nix, but as long as the npm dependencies all work on Windows there shouldn't be anything preventing it building.

I've pushed I fix to the package.json, adding "node" to the start of the build lines. I don't have a Windows box to test on ATM, so will leave this issue open till I can test myself or get confirmation it works.

Cheers!
